### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Robbie84625**
網址：http://54.193.6.131:3000/ 姓名：劉宣甫 discode:robbie84625

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by Robbie84625** [comment]
Sorry, I just did another test and can now log in to my server.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your server goes down after some requests.
2. We have to show proper error message when we try to sign up with repeated email.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
